=== api-evangelist/university-of-calgary/json-schema/university-of-calgary-dataset-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/university-of-calgary/main/json-schema/university-of-calgary-dataset-schema.json",
  "title": "Dataset",
  "description": "A UCalgary Space Remote Sensing data distribution dataset.",
  "type": "object",
  "properties": {
    "name": {
      "type": "string",
      "description": "Unique dataset name/identifier."
    },
    "short_description": {
      "type": "string"
    },
    "long_description": {
      "type": "string"
    },
    "data_tree_url": {
      "type": "string",
      "format": "uri"
    },
    "file_listing_supported": {
      "type": "boolean"
    },
    "level": {
      "type": "string",
      "description": "Processing level (e.g. L0, L1)."
    },
    "doi": {
      "type": [
        "string",
        "null"
      ],
      "format": "uri"
    },
    "doi_details": {
      "type": [
        "string",
        "null"
      ]
    },
    "citation": {
      "type": [
        "string",
        "null"
      ]
    },
    "supported_libraries": {
      "type": "array",
      "items": {
        "type": "string",
        "enum": [
          "pyaurorax",
          "pyucrio",
          "idl-aurorax",
          "idl-ucrio",
          "pyucalgarysrs"
        ]
      }
    },
    "file_time_resolution": {
      "type": "string",
      "enum": [
        "1min",
        "1hr",
        "1day",
        "not_applicable"
      ]
    }
  },
  "required": [
    "name",
    "short_description",
    "long_description",
    "data_tree_url",
    "file_listing_supported",
    "level",
    "file_time_resolution"
  ]
}

=== api-evangelist/university-of-calgary/examples/university-of-calgary-datasets-example.json
{
  "name": "NORSTAR_RIOMETER_K0_TXT",
  "short_description": "NORSTAR Single Frequency Riometers K0 raw data, in ASCII format",
  "long_description": "NORSTAR Single Frequency Single Beam Riometer array. More information can be found at https://data.phys.ucalgary.ca",
  "data_tree_url": "https://data.phys.ucalgary.ca/sort_by_project/GO-Canada/GO-Rio/txt",
  "file_listing_supported": true,
  "level": "L0",
  "doi": "https://doi.org/10.11575/AFYX-M516",
  "doi_details": "https://commons.datacite.org/doi.org/10.11575/afyx-m516",
  "citation": "Spanswick, E., Wallis, D., Donovan, E., & Jackel, B. NORSTAR Single Frequency Single Beam Riometers Dataset [Data set]. University of Calgary. https://doi.org/10.11575/AFYX-M516",
  "supported_libraries": [
    "idl-ucrio",
    "pyucalgarysrs",
    "pyucrio"
  ],
  "file_time_resolution": "1day"
}
